image: dbp1/ghc-7.8.3-postgres-git
script:
  - psql -c 'create database skilltree_test;' -U postgres -h 127.0.0.1
  - psql -c "create user skilltree_user with password '111' superuser"
  - cd / && git clone https://github.com/dbp/migrate migrate; true
  - cd /migrate && cabal sandbox init && cabal install
  - /migrate/.cabal-sandbox/bin/migrate up test
  - cd / && mkdir sandbox && cd /sandbox && cabal sandbox init
  - cabal install --only-dependencies --enable-tests --sandbox-config-file=/sandbox/cabal.sandbox.config
  - cabal exec --sandbox-config-file=/sandbox/cabal.sandbox.config -- runghc -isrc src/Test.hs
services:
  - postgres
cache:
  - /migrate
  - /sandbox
notify:
  email:
    recipients:
      - dbp@dbpmail.net
