image: dbp1/ghc-7.8.3-postgres-git
script:
  - apt-get install syslinux -y
  - echo `gethostip -d $HOSTNAME`
  - socat TCP-LISTEN:5432,fork TCP:`gethostip -d $HOSTNAME`:5432 &
  - psql -c 'create database skilltree_test;' -U postgres -h 127.0.0.1
  - psql -c "create user skilltree_user with password '111' superuser" -U postgres -h 127.0.0.1
  - cabal update
  - if [ ! -d "/migrate" ] ; then git clone https://github.com/dbp/migrate migrate /migrate; fi
  - pushd /migrate
  - cabal sandbox init && cabal install
  - popd
  - mkdir -p /sandbox && pushd /sandbox && cabal sandbox init && popd
  - cabal --sandbox-config-file=/sandbox/cabal.sandbox.config install --only-dependencies --enable-tests
  - /migrate/.cabal-sandbox/bin/migrate up test
  - cabal --sandbox-config-file=/sandbox/cabal.sandbox.config exec -- runghc -isrc spec/Main.hs
services:
  - postgres
cache:
  - /migrate
  - /sandbox
notify:
  email:
    recipients:
      - dbp@dbpmail.net
