image: dbp1/ghc-7.8.3-migrate-rivet
script:
  - socat TCP-LISTEN:5432,fork TCP:`gethostip -d $HOSTNAME`:5432 &
  - psql -c 'create database skilltree_test;' -U postgres -h 127.0.0.1
  - psql -c "create user skilltree_user with password '111' superuser" -U postgres -h 127.0.0.1
  - cabal update
  - mkdir -p /sandbox && pushd /sandbox && cabal sandbox init && popd
  - ln -s /sandbox/.cabal-sandbox .
  - rivet setup
  - migrate up test
  - cabal exec -- runghc -isrc spec/Main.hs
services:
  - postgres
cache:
  - /sandbox