image: dbp1/ghc-7.8.3-postgres-git
script:
  - apt-get install syslinux -y
  - socat TCP-LISTEN:5432,fork TCP:`gethostip -d $HOSTNAME`:5432 &
  - psql -c 'create database skilltree_test;' -U postgres -h 127.0.0.1
  - psql -c "create user skilltree_user with password '111' superuser" -U postgres -h 127.0.0.1
  - cabal update
  - if [ ! -d "/migrate" ] ; then git clone https://github.com/dbp/migrate /migrate; fi
  - pushd /migrate
  - cabal sandbox init && cabal install
  - popd
  - rm -rf /rivet
  - if [ ! -d "/rivet" ] ; then git clone https://github.com/dbp/rivet /rivet; fi
  - pushd /rivet
  - ls -l
  - cabal sandbox init && cabal install
  - popd
  - /rivet/.cabal-sandbox/bin/rivet setup
  - /migrate/.cabal-sandbox/bin/migrate up test
  - cabal exec -- runghc -isrc spec/Main.hs
services:
  - postgres
#cache:
#  - /migrate
#  - /rivet
notify:
  email:
    recipients:
      - dbp@dbpmail.net
