image: dbp1/ghc-7.8.3-migrate-rivet
script:
  - socat TCP-LISTEN:5432,fork TCP:`gethostip -d $HOSTNAME`:5432 &
  - psql -c 'create database skilltree_test;' -U postgres -h 127.0.0.1
  - psql -c "create user skilltree_user with password '111' superuser" -U postgres -h 127.0.0.1
  - cabal update
  - mkdir -p /sandbox && pushd /sandbox && cabal sandbox init && popd
  - ln -s /sandbox/.cabal-sandbox .
  - rivet setup
  - migrate up test
  - apt-get install redis-server -y
  - redis-server &
  - cabal exec -- runghc -isrc spec/Main.hs
  # NOTE(dbp 2014-09-17): The following are to set up for (a potential) publish build.
  - echo `/sbin/ip route|awk '/default/ { print $3 }'` dockerhost >> /etc/hosts
  - mv docker/Dockerfile.production Dockerfile
services:
  - postgres
cache:
  - /sandbox
publish:
  docker:
    docker_server: dockerhost
    docker_port: 2375
    docker_version: 1.2.0
    registry_login: true
    username: {{hubUsername}}
    password: {{hubPassword}}
    email: {{hubEmail}}
    image_name: dbp1/skilltree_production
    keep_build: false
    branch: master
deploy:
  bash:
    script:
    # NOTE(dbp 2014-09-18): There isn't any way of restricting deploy
    # to a branch, so the plan is just that the tag shouldn't have an
    # image on other branches (as they should be ahead or on a
    # different path from master). A little annoying, but what are you
    # going to do.
      - ssh host@stage.skilltree.dbpapp.com /srv/deploy.sh skilltree stage dbp1/skilltree_production $(git rev-parse --short HEAD) 1; echo 0
notify:
  email:
    recipients:
      - dbp@dbpmail.net
      - mattraibert@gmail.com