---
- hosts: stage
  gather_facts: yes

  sudo: no

  vars_files:
    - secrets.yml

  vars:
    user: host

  roles:
    - angstwad.docker_ubuntu
    - postgresql
    - redis
    - { role: tarsnap, when: env == "prod" }
    - nginx
    - confd
    - common