#!/bin/bash
PG_VERSION="9.3"
PG_CONFDIR="/etc/postgresql/${PG_VERSION}/main"
PG_BINDIR="/usr/lib/postgresql/${PG_VERSION}/bin"
PG_DATADIR="/var/lib/postgresql/${PG_VERSION}/main"

# fix permissions and ownership of /var/lib/postgresql
chown -R postgres:postgres /var/lib/postgresql
chmod 700 /var/lib/postgresql

# fix permissions and ownership of /var/run/postgresql
chown -R postgres:postgres /var/run/postgresql
chmod 775 /var/run/postgresql
chmod g+s /var/run/postgresql


if [ ! -d ${PG_DATADIR} ]; then
    echo "Initializing database..."
    PG_PASSWORD=111
    echo "${PG_PASSWORD}" > /var/lib/postgresql/pwfile
    sudo -u postgres -H "${PG_BINDIR}/initdb" \
        --pgdata="${PG_DATADIR}" --pwfile=/var/lib/postgresql/pwfile \
        --username=postgres --encoding=unicode --auth=trust >/dev/null
    /usr/sbin/service postgresql start
    sudo -u postgres psql template1 -c "CREATE USER skilltree_user WITH PASSWORD '111'"
    sudo -u postgres psql template1 -c "CREATE DATABASE skilltree_devel"
    sudo -u postgres psql template1 -c "GRANT ALL ON DATABASE skilltree_devel TO skilltree_user"
    sudo -u postgres psql template1 -c "CREATE DATABASE skilltree_test"
    sudo -u postgres psql template1 -c "GRANT ALL ON DATABASE skilltree_test TO skilltree_user"
else
    /usr/sbin/service postgresql start
fi

/srv/dist/build/skilltree/skilltree --no-access-log --no-error-log
