[template]
keys = [
"skilltree/{{env}}/upstream",
]
owner = "nginx"
mode = "0644"
src = "nginx-skilltree-{{env}}.tmpl"
dest = "/etc/nginx/sites-enabled/skilltree-{{env}}.conf"
check_cmd = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/service nginx reload"
